version: '3.1'
services:
  mongo:
    container_name: geo-mongo
    image: mongo
    ports:
      - 27017:27017

  springboot:
    build: .
    container_name: geo-springboot
    image: task-geo
    restart: always
    ports:
      - 9000:9000
    depends_on:
      - mongo