version: '3.1'
services:
  mongo:
    container_name: geo-mongo
    image: mongo
    ports:
      - 27017:27017
    expose:
      - "27017"

  springboot:
    container_name: geo-springboot
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 9000:9000
    expose:
      - "9000"
    command: mvn clean spring-boot:run -Dspring-boot.run.arguments=--spring.data.mongodb.uri=mongodb://webflux:password@my-mongo:27017/geotask
    depends_on:
      - mongo