spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  data:
    mongodb:
      uri: mongodb://webflux:password@localhost:27017/geotask
server:
  port: 9000